import { Artwork, Collection, CollectorMoodConfig, RoomScene } from "./types";

// Helper to construct exact URL-safe links to the uploaded JPG images served by the Express backend.
const buildImageUrl = (fileName: string) => `/images-upload/${encodeURIComponent(fileName)}`;

export const MASTER_ARTWORKS: Artwork[] = [
  {
    id: "magnum-officer-ankle-1979",
    title: "An officer removes his ankle revolver, New York City, 1979",
    artist: "Leonard Freed",
    artistShort: "Leonard Freed",
    year: "1979",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Vintage Silver Gelatin Print",
    description: "An intimate, raw glimpse behind the official shield, capturing the quiet post-shift transition of a Brooklyn patrol officer.",
    details: "Shot with a Leica rangefinder on high-speed Tri-X film. Leonard Freed spent years documenting the complex lives of New York City law enforcement, treating his subjects with quiet dignity and deep psychological curiosity.",
    mood: "Contemplative",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: An officer removes his ankle revolver, New York City, 1979\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=1200",
    lightingColor: "rgba(138, 106, 69, 0.35)",
    shadowOffset: "translate(20px, 20px) blur(35px)",
    scale: 0.82,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-arnold-la-1977",
    title: "Arnold Schwarzenegger, LA, 1977",
    artist: "Thomas Hoepker",
    artistShort: "Thomas Hoepker",
    year: "1977",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Archival Pigment Print on Hahnemühle Baryta Paper",
    description: "An iconic capture of the legendary bodybuilder posing in Venice Beach, California. Hoepker captures both muscle power and quiet human vulnerability.",
    details: "This signature photograph was taken while Arnold Schwarzenegger was preparing to transition from bodybuilding champion to Hollywood actor. It represents the height of physical sculpture captured with journalistic intimacy.",
    mood: "Power",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: Arnold Schwarzenegger, LA, 1977\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1560243563-062bfc001d68?q=80&w=1200",
    lightingColor: "rgba(216, 210, 198, 0.4)",
    shadowOffset: "translate(10px, 20px) blur(25px)",
    scale: 0.85,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-audrey-paris-1956",
    title: "Audrey Hepburn in Paris, 1956",
    artist: "Dennis Stock",
    artistShort: "Dennis Stock",
    year: "1956",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Sovereign Fine Art Matte Print",
    description: "The epitome of mid-century cinematic charm: Audrey Hepburn walking alongside the Seine, captured in effortless Parisian elegance.",
    details: "Dennis Stock, famous for his intimate portraits of Hollywood personalities, presents Hepburn not as an untouchable icon, but as an inquisitive soul interacting naturally with French light.",
    mood: "Royal",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Audrey Hepburn in Paris, 1956\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200",
    lightingColor: "rgba(240, 235, 220, 0.55)",
    shadowOffset: "translate(-18px, 22px) blur(30px)",
    scale: 0.92,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-belfast-1972",
    title: "Belfast, Northern Ireland, 1972",
    artist: "Philip Jones Griffiths",
    artistShort: "Philip Jones Griffiths",
    year: "1972",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Estate Stamped Silver Gelatin Print",
    description: "A deeply historic, striking, and silent scene capturing local life persisting amidst urban borders in Northern Ireland.",
    details: "Griffiths, a renowned Welsh photojournalist, captures the sheer emotional landscape of daily life inside a historical zone. The post-industrial brick textures offer unique depth.",
    mood: "Contemplative",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: Belfast, Northern Ireland, 1972\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?q=80&w=1200",
    lightingColor: "rgba(180, 180, 180, 0.3)",
    shadowOffset: "translate(12px, 12px) blur(20px)",
    scale: 0.8,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-berlin-wall-1989",
    title: "Berlin, Germany after the fall of the wall on Sunday, 31 December, 1989",
    artist: "Thomas Hoepker",
    artistShort: "Thomas Hoepker",
    year: "1989",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Estate Stamped Matted Fiber Print",
    description: "West and East Berliners gathering to climb the wall in absolute relief. A supreme physical document of historical transition.",
    details: "Hoepker arrived at the Berlin Wall as history unfolded. This piece represents the raw concrete texture of liberation, capturing the dusty air of people breaking down historic borders.",
    mood: "Mystery",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: Berlin, Germany after the fall of the wall on Sunday, 31 December, 1989\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?q=80&w=1200",
    lightingColor: "rgba(100, 100, 100, 0.4)",
    shadowOffset: "translate(25px, 30px) blur(30px)",
    scale: 0.86,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-black-panthers-1969",
    title: "Black Panthers protesting in Chicago, Illinois, 1969",
    artist: "Hiroji Kubota",
    artistShort: "Hiroji Kubota",
    year: "1969",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Vintage Fiber-Based Double-Weight Print",
    description: "A commanding group silhouette representing civil rights architecture and unified structural voice in the Chicago winter.",
    details: "Kubota documented these historic rallies with immense visual grace, casting heavy shadows that merge with modern concrete brutalist surroundings, turning street journalism into monumental classical compositions.",
    mood: "Power",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: Black Panthers protesting in Chicago, Illinois, 1969\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?q=80&w=1200",
    lightingColor: "rgba(224, 218, 208, 0.45)",
    shadowOffset: "translate(-15px, 20px) blur(30px)",
    scale: 0.9,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-cincinnati-2018",
    title: "Cincinnati, Ohio, 2018",
    artist: "Alec Soth",
    artistShort: "Alec Soth",
    year: "2018",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Limited Edition Chromogenic Print",
    description: "An elegant, minimalist inquiry into Midwestern landscape and quiet architectural geometry.",
    details: "Part of Soth's series on contemporary American spaces, seeking silence and structural introspection in places that are often ignored. Excellent for calming visual anchors.",
    mood: "Calm",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: Cincinnati, Ohio, 2018\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=1200",
    lightingColor: "rgba(236, 231, 223, 0.4)",
    shadowOffset: "translate(10px, 15px) blur(20px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-daytona-1997",
    title: "Daytona Beach, Florida, 1997",
    artist: "Constantine Manos",
    artistShort: "Constantine Manos",
    year: "1997",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Cibachrome Museum Quality Print",
    description: "A magnificent play of sunbeams, physical rest, and heavy shadows at the historic Floridan coastline. A masterwork of color contrast translated to pristine B&W.",
    details: "Manos utilized highly saturated film which when stripped to monochrome showcases incredible depth in midtones. It turns a trivial vacation into a profound spatial geometry of human rest.",
    mood: "Spiritual",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: Daytona Beach, Florida, 1997\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200",
    lightingColor: "rgba(215, 210, 200, 0.4)",
    shadowOffset: "translate(15px, 25px) blur(35px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-jazz-france-1985",
    title: "Dexter Gordon, Freddie Hubbard and Ron Carter in France, 1985",
    artist: "Guy Le Querrec",
    artistShort: "Guy Le Querrec",
    year: "1985",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Double-Weight Silver Gelatin Print",
    description: "The physical form of rhythm: three jazz legends captured in an extraordinary moment of smoky, low-key acoustic collaboration.",
    details: "A legendary musical document. Le Querrec's lens behaves like a musician itself, capturing the split-second sync of trumpet bells and double bass curves under soft stage spotlights.",
    mood: "Mystery",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Dexter Gordon, Freddie Hubbard and Ron Carter in France, 1985\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1200",
    lightingColor: "rgba(120, 110, 100, 0.5)",
    shadowOffset: "translate(30px, 30px) blur(40px)",
    scale: 0.96,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-disco-wolverhampton-1978",
    title: "Disco in Wolverhampton, England, 1978",
    artist: "Chris Steele-Perkins",
    artistShort: "Chris Steele-Perkins",
    year: "1978",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Archival Silver Gelatin Print",
    description: "Sovereign youth: capturing British youth subculture with dynamic kinetic sweep on a crowded dance floor in 1978.",
    details: "Steele-Perkins documented the raw and energetic fashion movements of late-70s England. This image turns active human motion into structured geometry.",
    mood: "Royal",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: Disco in Wolverhampton, England, 1978\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200",
    lightingColor: "rgba(220, 215, 205, 0.45)",
    shadowOffset: "translate(-22px, 22px) blur(28px)",
    scale: 0.94,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-taylor-set-1959",
    title: "Elizabeth Taylor on the set of “Suddenly Last Summer”, 1959",
    artist: "Burt Glinn",
    artistShort: "Burt Glinn",
    year: "1959",
    size: "20 x 24 in (50.8 x 61.0 cm)",
    medium: "Estate Stamped Silver Gelatin Print",
    description: "An aristocratic, breathtaking portrait of classic Hollywood lineage caught between scenes in natural shadows.",
    details: "Glinn's legendary documentation of high fashion and cinema production. This piece boasts deeply rich silver halide tones that fit perfectly in classical layouts.",
    mood: "Royal",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Elizabeth Taylor on the set of “Suddenly Last Summer”, 1959\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1200",
    lightingColor: "rgba(240, 235, 220, 0.55)",
    shadowOffset: "translate(-18px, 22px) blur(30px)",
    scale: 0.92,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-fashion-corps-1973",
    title: "Fashion show at the Israeli Women’s Corps, 1973",
    artist: "Micha Bar-Am",
    artistShort: "Micha Bar-Am",
    year: "1973",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Lifetime Silver Gelatin Fiber Print",
    description: "A striking, unusual convergence of military architecture, geometric lines, and haute couture clothing.",
    details: "Bar-Am was famous for capturing historical ironies in physical composition. Here, structured military ranks create physical perspective lines directing focus to high fashion elements.",
    mood: "Power",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Fashion show at the Israeli Women’s Corps, 1973\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1200",
    lightingColor: "rgba(224, 218, 208, 0.45)",
    shadowOffset: "translate(-15px, 20px) blur(30px)",
    scale: 0.9,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-lauderdale-1966",
    title: "Fort Lauderdale, Florida, 1966",
    artist: "René Burri",
    artistShort: "René Burri",
    year: "1966",
    size: "12 x 16 in (30.5 x 40.6 cm)",
    medium: "Museum Quality Fiber-Based Print",
    description: "Graceful palm trees bent in absolute geometric synchronization against the hazy, high-key Florida coastline.",
    details: "René Burri was a master of using natural vertical architecture to layer his compositions. This peaceful but powerful image transforms a landscape into an element of graphic design.",
    mood: "Calm",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: Fort Lauderdale, Florida, 1966\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1200",
    lightingColor: "rgba(235, 230, 222, 0.5)",
    shadowOffset: "translate(15px, 15px) blur(20px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-march-gentlemen-2017",
    title: "From the series ‘The First March of Gentlemen’, 2017",
    artist: "Rafal Milach",
    artistShort: "Rafal Milach",
    year: "2017",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Fine Art Matte Archival Pigment",
    description: "An elegant, surrealist visual essay examining memory, history, and social uniformity in contemporary Poland.",
    details: "Milach uses theatrical lighting and stark, geometric alignment to turn physical human alignments into surrealist, quiet statues.",
    mood: "Contemplative",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: From the series ‘The First March of Gentlemen’, 2017\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200",
    lightingColor: "rgba(138, 106, 69, 0.35)",
    shadowOffset: "translate(20px, 20px) blur(35px)",
    scale: 0.82,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-harlem-1963",
    title: "Harlem, New York, 1963",
    artist: "Cornell Capa",
    artistShort: "Cornell Capa",
    year: "1963",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Estate Prints Exhibition Silver Gelatin",
    description: "Sidewalk life in Harlem, capturing raw social warmth, grit, and the elegant, rhythmic pacing of Manhattan's cultural capital.",
    details: "A classic street-level masterpiece by Capa, showing the structural geometry of fire escapes, brick masonry, and deep urban shadows.",
    mood: "Contemplative",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: Harlem, New York, 1963\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1514924013511-28c34309c0f9?q=80&w=1200",
    lightingColor: "rgba(180, 180, 180, 0.3)",
    shadowOffset: "translate(12px, 12px) blur(20px)",
    scale: 0.8,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-havana-webb-2014",
    title: "Havana, Cuba, 2014",
    artist: "Alex Webb",
    artistShort: "Alex Webb",
    year: "2014",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Museum Chromogenic Print",
    description: "A classic example of complex Webb framing, mapping sharp spatial shadows and deep silhouettes in Havana's back alleys.",
    details: "Webb's work relies on high-contrast lighting ratios. Even when seen in classic monochrome values, it reveals deep layers of city architecture and human presence.",
    mood: "Mystery",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: Havana, Cuba, 2014\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1200",
    lightingColor: "rgba(120, 110, 100, 0.5)",
    shadowOffset: "translate(30px, 30px) blur(40px)",
    scale: 0.96,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-james-dean-1955",
    title: "James Dean in Times Square, 1955",
    artist: "Dennis Stock",
    artistShort: "Dennis Stock",
    year: "1955",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Lifetime Signed Gelatin Print",
    description: "One of the most famous actor portraits ever taken: James Dean walking through a rain-slicked Times Square, coat collar upturned.",
    details: "This supreme snapshot captures the ultimate mood of introverted youth culture. The towering wet pavements of 1950s Manhattan provide a massive vertical backdrop.",
    mood: "Contemplative",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: James Dean in Times Square, 1955\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?q=80&w=1200",
    lightingColor: "rgba(138, 106, 69, 0.35)",
    shadowOffset: "translate(20px, 20px) blur(35px)",
    scale: 0.82,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-marilyn-set-1960",
    title: "Marilyn Monroe on the set of “The Misfits”, 1960",
    artist: "Eve Arnold",
    artistShort: "Eve Arnold",
    year: "1960",
    size: "20 x 24 in (50.8 x 61.0 cm)",
    medium: "Estate Stamped Archival Silver Gelatin Print",
    description: "A legendary candid moment of Marilyn Monroe practicing lines on set, bathed in completely natural direct desert sunlight.",
    details: "Eve Arnold was one of Marilyn's most trusted friends. This portrait bypasses commercial studio layouts to find her in a state of intellectual contemplation in Nevada.",
    mood: "Spiritual",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Marilyn Monroe on the set of “The Misfits”, 1960\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200",
    lightingColor: "rgba(220, 212, 200, 0.45)",
    shadowOffset: "translate(12px, 26px) blur(28px)",
    scale: 0.95,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-marilyn-rest-1960",
    title: "Marilyn Monroe rests in between takes during the filming of The Misfits, Nevada, 1960",
    artist: "Eve Arnold",
    artistShort: "Eve Arnold",
    year: "1960",
    size: "20 x 24 in (50.8 x 61.0 cm)",
    medium: "Traditional Gelatin Silver Fiber Print",
    description: "A close-up of Marilyn resting gracefully against a trailer, displaying raw human rest and peaceful light play.",
    details: "This historical masterpiece encapsulates the quiet, beautiful margin that exists between artificial film-set lighting and absolute, unscripted reality.",
    mood: "Spiritual",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Marilyn Monroe rests in between takes during the filming of The Misfits, Nevada, 1960\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1200",
    lightingColor: "rgba(215, 210, 200, 0.4)",
    shadowOffset: "translate(15px, 25px) blur(35px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-miami-beach-2003",
    title: "Miami Beach, Florida, 2003",
    artist: "Martin Parr",
    artistShort: "Martin Parr",
    year: "2003",
    size: "20 x 24 in (50.8 x 61.0 cm)",
    medium: "Archival Pigment Print",
    description: "A witty, minimal visual analysis of beach-umbrella geometries and resting coastal silhouettes.",
    details: "Parr is celebrated for his photographic satire. When framed in sharp monochrome values, this beachscape becomes a striking graphic sculpture pattern.",
    mood: "Calm",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: Miami Beach, Florida, 2003\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200",
    lightingColor: "rgba(236, 231, 223, 0.4)",
    shadowOffset: "translate(10px, 15px) blur(20px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-ali-chicago-1966",
    title: "Muhammad Ali, Chicago river, Illinois, 1966",
    artist: "Thomas Hoepker",
    artistShort: "Thomas Hoepker",
    year: "1966",
    size: "20 x 24 in (50.8 x 61.0 cm)",
    medium: "Estate Stamped Archival Silver Gelatin Print",
    description: "The supreme boxing champion displaying his fist in supreme focus over the Chicago River. A study of defiance.",
    details: "One of the most reproduced sports photographs of the 20th century. Taken during a private session, this masterpiece focuses entirely on the physical architecture of human determination.",
    mood: "Power",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: Muhammad Ali, Chicago river, Illinois, 1966\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1200",
    lightingColor: "rgba(224, 218, 208, 0.45)",
    shadowOffset: "translate(-15px, 20px) blur(30px)",
    scale: 0.9,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-nypd-officer-1978",
    title: "NYPD Officer, New York City, 1978",
    artist: "Leonard Freed",
    artistShort: "Leonard Freed",
    year: "1978",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Vintage Exhibition Gelatin Silver Print",
    description: "A stunning compositional portrait of urban control, framing an officer standing beside his cruiser doors in Manhattan.",
    details: "Freed's photojournalism was celebrated for finding warm, raw human stories in stressful public environments. This shot highlights the physical silhouette of authority.",
    mood: "Contemplative",
    collection: "Street",
    imageUrl: buildImageUrl("Magnum Editions: NYPD Officer, New York City, 1978\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1200",
    lightingColor: "rgba(180, 180, 180, 0.3)",
    shadowOffset: "translate(12px, 12px) blur(20px)",
    scale: 0.8,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-guggenheim-venice-1950",
    title: "Peggy Guggenheim in Venice, 1950",
    artist: "David Seymour",
    artistShort: "David Seymour",
    year: "1950",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Estate Prints Exhibition Silver Gelatin Print",
    description: "The celebrated art patroness Peggy Guggenheim relaxing on her private Venetian terrace overlooking the canal.",
    details: "Seymour captures Guggenheim with her beloved Lhasa Apso dogs. The background canal waters form a glittering backplane reflecting elite cultural heritage.",
    mood: "Royal",
    collection: "Portraits",
    imageUrl: buildImageUrl("Magnum Editions: Peggy Guggenheim in Venice, 1950\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=1200",
    lightingColor: "rgba(220, 215, 205, 0.45)",
    shadowOffset: "translate(-22px, 22px) blur(28px)",
    scale: 0.94,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-sao-paulo-1960",
    title: "São Paulo, Brazil, 1960",
    artist: "René Burri",
    artistShort: "René Burri",
    year: "1960",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Limited Edition Hand Pressed Print",
    description: "An extraordinary masterwork of volumetric shadow play, capturing tiny human silhouettes walking across skyscraper roofs.",
    details: "Perhaps René Burri's most celebrated architectural photo. The sheer, steep vertical drops and structural shadow blocks create a monument of concrete modernist elegance.",
    mood: "Power",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: São Paulo, Brazil, 1960\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200",
    lightingColor: "rgba(224, 218, 208, 0.45)",
    shadowOffset: "translate(-15px, 20px) blur(30px)",
    scale: 0.9,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-tangiers-1995",
    title: "Tangiers, Morocco, 1995",
    artist: "Bruno Barbey",
    artistShort: "Bruno Barbey",
    year: "1995",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Archival C-Type Fiber Print",
    description: "A tranquil silhouette walking past beautiful Medina archways. A study of slow-fading Arabian late afternoon light.",
    details: "Barbey's Morocco series is world-famous for its incredible mastery of shadow geometry, bringing exceptional visual warm and historical weight to quiet pavilions.",
    mood: "Spiritual",
    collection: "Atmospheres",
    imageUrl: buildImageUrl("Magnum Editions: Tangiers, Morocco, 1995\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?q=80&w=1200",
    lightingColor: "rgba(215, 210, 200, 0.4)",
    shadowOffset: "translate(15px, 25px) blur(35px)",
    scale: 0.88,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  },
  {
    id: "magnum-west-berlin-1965",
    title: "Youth in West Berlin, 1965",
    artist: "Leonard Freed",
    artistShort: "Leonard Freed",
    year: "1965",
    size: "16 x 20 in (40.6 x 50.8 cm)",
    medium: "Estate Stamped Silver Gelatin Print",
    description: "Youth walking around the ruins of post-war Germany, displaying sharp, cool-headed defiant physical presence.",
    details: "This striking photograph details both the gritty pavement of Berlin and the iconic leather-jacket rebellion of the mid-1960s generation.",
    mood: "Mystery",
    collection: "Archive",
    imageUrl: buildImageUrl("Magnum Editions: Youth in West Berlin, 1965\nRegular price\n$400.00 - $595.00\n.jpg"),
    fallbackUrl: "https://images.unsplash.com/photo-1505022610485-0249ba5b3675?q=80&w=1200",
    lightingColor: "rgba(100, 100, 100, 0.4)",
    shadowOffset: "translate(25px, 30px) blur(30px)",
    scale: 0.86,
    priceRange: "$400.00 – $595.00",
    availability: "In stock"
  }
];

export const EMOTIONAL_COLLECTIONS: Collection[] = [
  {
    id: "col-street",
    name: "Street Life",
    tagline: "The Poetry of the Pavement",
    description: "Gritty New York officers, Belfast kids, and elegant Times Square silhouettes captured by legendary rangefinders.",
    atmosphere: "An urban loft filled with concrete, steel rafters, and dramatic city street reflections.",
    bgClass: "bg-[#0F0F0D] text-[#ECE7DF]",
    textClass: "text-[#D8D1C7]",
    lightingClass: "from-[#8A6A45]/20 to-transparent",
    fontFamily: "font-[Space_Grotesk]"
  },
  {
    id: "col-portraits",
    name: "Classic Portraits",
    tagline: "Sovereign Heritage",
    description: "Candid historical insights of cultural giants from Audrey Hepburn to Marilyn Monroe in gorgeous studio clarity.",
    atmosphere: "A silent museum wing of marble partitions under individual focused picture spotlights.",
    bgClass: "bg-[#141416] text-[#ECE7DF]",
    textClass: "text-[#ECE7DF]",
    lightingClass: "from-[#D8D1C7]/15 to-transparent",
    fontFamily: "font-[Playfair_Display]"
  },
  {
    id: "col-atmospheres",
    name: "Atmospheres",
    tagline: "The Geometry of Space",
    description: "Serene Floridan beaches and architectural roof structures turning geography into timeless graphic design composition.",
    atmosphere: "A towering seaside pavilion built of white limestone, completely exposed to bright afternoon sea spray.",
    bgClass: "bg-[#ECE7DF] text-[#0A0A0A]",
    textClass: "text-[#0A0A0A]",
    lightingClass: "from-white/40 to-transparent",
    fontFamily: "font-[Inter]"
  },
  {
    id: "col-archive",
    name: "Historic Archive",
    tagline: "Quiet Burdens of History",
    description: "Arnold Schwarzenegger preparing for Hollywood, Black Panthers in Chicago, and post-war Berlin preserve moments of truth.",
    atmosphere: "A quiet academic study lined with dark mahogany bookshelves and vintage paper textures.",
    bgClass: "bg-[#090909] text-[#D8D1C7]",
    textClass: "text-[#D8D1C7]",
    lightingClass: "from-zinc-800/50 to-transparent",
    fontFamily: "font-[Fira_Code]"
  }
];

export const COLLECTOR_MOOD_CONFIGS: CollectorMoodConfig[] = [
  {
    mood: "Calm",
    title: "Coastline Silence",
    background: "bg-[#ECE7DF]",
    textColor: "text-[#0A0A0A]",
    accentColor: "border-[#8A6A45] text-[#8A6A45]",
    lightingGlow: "rgba(236, 231, 223, 0.4)",
    ambientHumHz: 110, // A2 note
    harmonicHz: 220,
    description: "Rebalances your living room with light-catching fiber grains, beach-washed high key tones, and a serene visual atmosphere."
  },
  {
    mood: "Power",
    title: "Anatomical Gravity",
    background: "bg-[#0A0A0A]",
    textColor: "text-[#ECE7DF]",
    accentColor: "border-neutral-700 text-neutral-400",
    lightingGlow: "rgba(138, 106, 69, 0.35)",
    ambientHumHz: 82.4, // E2 note for deep architectural drone
    harmonicHz: 164.8,
    description: "Saturates your space with high-speed Tri-X grain, deep structural shadows, and peak athletic tension."
  },
  {
    mood: "Spiritual",
    title: "Timeless Clarity",
    background: "bg-gradient-to-b from-[#0A0A0A] to-[#1A1A1A]",
    textColor: "text-[#ECE7DF]",
    accentColor: "border-[#8A6A45] text-[#D8D1C7]",
    lightingGlow: "rgba(216, 209, 199, 0.5)",
    ambientHumHz: 130.8, // C3 note for sacred chanting frequencies
    harmonicHz: 196.0, // G3 pure fifth harmonic
    description: "Restores mental clarity through the divine smiling faces of icons bathed in completely natural skylight."
  },
  {
    mood: "Mystery",
    title: "Smoked Obsidian Archive",
    background: "bg-[#050505]",
    textColor: "text-[#D8D1C7]",
    accentColor: "border-zinc-800 text-zinc-500",
    lightingGlow: "rgba(26, 26, 26, 0.95)",
    ambientHumHz: 73.4, // D2 note, heavy and cinematic
    harmonicHz: 110.0,
    description: "Enwraps the room in the deep, aromatic aura of Cuba, historic revolutions, and smoky silhouette borders."
  },
  {
    mood: "Royal",
    title: "Sovereign Heritage",
    background: "bg-radial from-[#1A1A1A] to-black",
    textColor: "text-[#ECE7DF]",
    accentColor: "border-amber-600 text-amber-500",
    lightingGlow: "rgba(138, 106, 69, 0.6)",
    ambientHumHz: 98.0, // G2 note for warm harmonies
    harmonicHz: 146.85,
    description: "Invents an absolute presence with mid-century elite movie sets and Venetian terrace legacies."
  },
  {
    mood: "Contemplative",
    title: "Urban Introspection",
    background: "bg-gradient-to-tr from-[#1A1A1A] via-[#101010] to-[#1F1D19]",
    textColor: "text-[#ECE7DF]",
    accentColor: "border-[#8A6A45] text-[#8A6A45]",
    ambientHumHz: 120.0,
    harmonicHz: 240.0,
    lightingGlow: "rgba(138, 106, 69, 0.25)",
    description: "Provides space for mental pacing alongside London's misty alleys and New York's taxi windshield reflections."
  }
];

export const ROOM_SCENES: RoomScene[] = [
  {
    id: "room-brutalist",
    name: "Tadao Ando Penthouse",
    description: "A gorgeous raw-concrete structure with sharp linear ceilings and single-spot skylights.",
    bgUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    wallColor: "bg-[#2A2B2D]/40",
    artworkScale: "scale-75",
    artOffsetClass: "top-[25%] left-[30%]"
  },
  {
    id: "room-villa",
    name: "High-Ceiling Mid-Century Salon",
    description: "An open-air luxury library lounge lined with warm teak wood and clean architectural beams.",
    bgUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200",
    wallColor: "bg-[#E6E1DA]/30",
    artworkScale: "scale-70",
    artOffsetClass: "top-[20%] left-[36%]"
  },
  {
    id: "room-vault",
    name: "Immersive Black Box Chamber",
    description: "A stark dark spatial sanctuary that focuses attention purely on the glowing paper fiber of the photographic print.",
    bgUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=1200",
    wallColor: "bg-black/80",
    artworkScale: "scale-80",
    artOffsetClass: "top-[18%] left-[32%]"
  }
];
